[general]
import = ["~/.config/alacritty/themes/terminal_app.toml"]

[font]
normal = { family = "IosevkaTermNerdFont", style = "Light" }
size = 17

# normal = { family = "UbuntuSansMonoNerdFontMono", style = "Retina" }
# size = 16.5

[window]
decorations = "None"
startup_mode = "Maximized"

# [colors]
# primary = { foreground = "#00ff0b" }
