[general]
import = ["~/.config/alacritty/themes/terminal_app.toml"]

[font]
# normal = { family = "IosevkaTermSlabNerdFont", style = "Regular" }
# size = 17

# normal = { family = "UbuntuSansMonoNerdFontMono", style = "Regular" }
# size = 16.5

normal = { family = "MonofurNerdFontMono", style = "Retina" }
size = 20

[window]
decorations = "None"
startup_mode = "Maximized"
