# This is a comment
# theme = "gruber-darker"
theme = "ayu_evolve"

[editor]
line-number = "relative"
text-width = 80
true-color = true
insert-final-newline = false
mouse = true
end-of-line-diagnostics = "hint"
continue-comments = true
soft-wrap.enable = true

[editor.inline-diagnostics]
cursor-line = "info"

[keys.normal]
o = ["open_below", "normal_mode"] # "o", "o<Esc>"
O = ["open_above", "normal_mode"] # "O", "O<Esc>"

[keys.insert]
j = {"k"= "normal_mode"}

[editor.indent-guides]
render = true
# character = "|"
character = "⸽" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.smart-tab]
enable = false
